# Generated by Django 6.1 on 2026-08-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(auto_created=True, blank=True, null=True, upload_to='', verbose_name='تصویر مکان')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان ها',
            },
        ),
    ]
